#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := draw_bitmaps

EXTRA_COMPONENT_DIRS := ${abspath ../../components}
BUILD_DIR_BASE := ${abspath ../../build}

include $(IDF_PATH)/make/project.mk
